import { Bot, InputFile, type Context } from 'grammy';
import type { ImageContent } from '@mariozechner/pi-ai';
import { config } from '../config.js';
import { drainPendingImages } from '../ai/image-tools.js';
import { chat } from '../ai/agent.js';
import type { ChatMessage } from '../ai/agent.js';
import { readMemory } from '../ai/memory.js';
import { createSession, listSessions, appendMessage, getSessionMessages } from '../ai/sessions.js';
import { getSessionId, setSessionId, clearSessionId, getAllChatIds } from './session-map.js';
import { markdownToTelegramHtml, splitMessage } from './format.js';
import { registerSendMessage, registerGetChatIds, registerOnAlertSent } from './alerts.js';

let bot: Bot | null = null;

function parseAllowedUsers(): Set<number> {
  if (!config.TELEGRAM_ALLOWED_USERS) return new Set();
  return new Set(
    config.TELEGRAM_ALLOWED_USERS.split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .map(Number),
  );
}

/** Send an HTML-formatted message, falling back to plain text on parse errors. */
async function replyHtml(ctx: Context, html: string): Promise<void> {
  try {
    await ctx.reply(html, { parse_mode: 'HTML' });
  } catch {
    await ctx.reply(html.replace(/<[^>]+>/g, ''));
  }
}

/** Resolve or create a session for a Telegram chat. */
function resolveSession(chatId: number): string {
  const existing = getSessionId(chatId);
  if (existing) return existing;
  const meta = createSession();
  setSessionId(chatId, meta.id);
  return meta.id;
}

const IMAGE_MIME_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/gif']);

/** Download a file from Telegram's API and return it as a base64-encoded ImageContent. */
async function downloadTelegramFile(fileId: string, mimeType: string): Promise<ImageContent> {
  const file = await bot!.api.getFile(fileId);
  const url = `https://api.telegram.org/file/bot${config.TELEGRAM_BOT_TOKEN}/${file.file_path}`;
  const res = await fetch(url);
  if (!res.ok) {
    await res.body?.cancel();
    throw new Error(`Failed to download file: ${res.statusText}`);
  }
  const buffer = Buffer.from(await res.arrayBuffer());
  return { type: 'image', data: buffer.toString('base64'), mimeType };
}

/** Shared handler: send user text (+ optional images) to the AI agent and reply. */
async function handleUserMessage(
  ctx: Context,
  text: string,
  images?: ImageContent[],
  historyText?: string,
): Promise<void> {
  const chatId = ctx.chat!.id;
  const sessionId = resolveSession(chatId);

  const history = getSessionMessages(sessionId) ?? [];
  appendMessage(sessionId, 'user', historyText ?? text);

  const conversationHistory: ChatMessage[] = [...history, { role: 'user', content: text }];

  const stopTyping = startTypingLoop(chatId, bot!.api);
  let result = '';

  try {
    for await (const event of chat(conversationHistory, images)) {
      if (event.type === 'result') {
        result = event.text;
      } else if (event.type === 'error') {
        throw new Error(event.text);
      }
    }

    if (result) {
      appendMessage(sessionId, 'assistant', result);
      const html = markdownToTelegramHtml(result);
      for (const chunk of splitMessage(html)) {
        await replyHtml(ctx, chunk);
      }
    } else {
      await ctx.reply('No response generated. Please try again.');
    }

    // Send any images generated by the generate_table_image tool
    for (const img of drainPendingImages()) {
      await ctx.replyWithPhoto(new InputFile(img.buffer, 'table.png'), {
        caption: img.caption,
      });
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : 'An error occurred';
    await ctx.reply(`Error: ${message}`);
  } finally {
    stopTyping();
  }
}

/** Send a typing indicator at regular intervals until cancelled. */
function startTypingLoop(chatId: number, api: Bot['api']): () => void {
  let timer: ReturnType<typeof setTimeout> | null = null;
  const tick = () => {
    api.sendChatAction(chatId, 'typing').catch(() => {});
    timer = setTimeout(tick, 4000);
  };
  tick();
  return () => {
    if (timer !== null) clearTimeout(timer);
  };
}

export function startTelegramBot(): void {
  if (!config.TELEGRAM_BOT_TOKEN) return;

  bot = new Bot(config.TELEGRAM_BOT_TOKEN);
  const allowedUsers = parseAllowedUsers();

  // Register alert infrastructure so alerts.ts can send messages
  const botRef = bot;
  registerSendMessage(async (chatId: number, html: string) => {
    try {
      await botRef.api.sendMessage(chatId, html, { parse_mode: 'HTML' });
    } catch {
      await botRef.api.sendMessage(chatId, html.replace(/<[^>]+>/g, ''));
    }
  });
  // Persist alert markdown into the user's active chat session so the
  // financial advisor has context if the user replies about the alert.
  // A synthetic user message is inserted when needed to maintain the
  // alternating user/assistant pattern that LLM APIs require.
  registerOnAlertSent((chatId: number, markdown: string, context?: string) => {
    const sessionId = resolveSession(chatId);
    const messages = getSessionMessages(sessionId);
    const lastRole = messages?.[messages.length - 1]?.role;
    if (!messages || messages.length === 0 || lastRole === 'assistant') {
      appendMessage(sessionId, 'user', context ?? '[Automated financial alert]');
    }
    appendMessage(sessionId, 'assistant', markdown);
  });
  registerGetChatIds(() => getAllChatIds());

  // ── Access control middleware ──
  if (allowedUsers.size === 0) {
    console.warn('TELEGRAM_ALLOWED_USERS is not set — Telegram bot will ignore all messages.');
    bot.use(() => {});
  } else {
    bot.use(async (ctx, next) => {
      const userId = ctx.from?.id;
      if (!userId || !allowedUsers.has(userId)) {
        return;
      }
      await next();
    });
  }

  // ── Commands ──

  bot.command('new', async (ctx) => {
    clearSessionId(ctx.chat.id);
    await ctx.reply('Session cleared. Your next message will start a new conversation.');
  });

  bot.command('memory', async (ctx) => {
    const memory = readMemory();
    if (!memory) {
      await ctx.reply('Memory is empty.');
      return;
    }
    for (const chunk of splitMessage(memory)) {
      await ctx.reply(chunk);
    }
  });

  bot.command('sessions', async (ctx) => {
    const sessions = listSessions();
    if (sessions.length === 0) {
      await ctx.reply('No sessions found.');
      return;
    }
    const currentSessionId = getSessionId(ctx.chat.id);
    const lines = sessions.slice(0, 20).map((s) => {
      const marker = s.id === currentSessionId ? ' (active)' : '';
      const shortId = s.id.slice(0, 8);
      return `${shortId}${marker} — ${s.title}`;
    });
    await ctx.reply(lines.join('\n'));
  });

  bot.command('switch', async (ctx) => {
    const partialId = ctx.match?.trim();
    if (!partialId) {
      await ctx.reply('Usage: /switch <session-id-prefix>');
      return;
    }
    const sessions = listSessions();
    const match = sessions.find((s) => s.id.startsWith(partialId));
    if (!match) {
      await ctx.reply(`No session found starting with "${partialId}".`);
      return;
    }
    setSessionId(ctx.chat.id, match.id);
    await ctx.reply(`Switched to session: ${match.title}`);
  });

  bot.command('alerts', async (ctx) => {
    const { loadAlertSettings } = await import('./alert-settings.js');
    const s = loadAlertSettings();
    const on = (v: boolean) => (v ? '✅' : '❌');
    const lines = [
      `**Alerts: ${on(s.enabled)}**`,
      `• Large charge threshold: ₪${s.largeChargeThreshold}`,
      `• Unusual spending threshold: ${s.unusualSpendingPercent}%`,
      `${on(s.monthlySummary.enabled)} Monthly summary (day ${s.monthlySummary.dayOfMonth})`,
      `${on(s.reportScrapeErrors)} Report scrape errors`,
    ];
    const html = markdownToTelegramHtml(lines.join('\n'));
    await replyHtml(ctx, html);
  });

  // ── Message handlers ──

  bot.on('message:text', async (ctx) => {
    const text = ctx.message.text;
    if (text.startsWith('/')) return;
    await handleUserMessage(ctx, text);
  });

  bot.on('message:photo', async (ctx) => {
    const photos = ctx.message.photo;
    const largest = photos[photos.length - 1];
    const caption = ctx.message.caption || "What's in this image?";

    try {
      const image = await downloadTelegramFile(largest.file_id, 'image/jpeg');
      await handleUserMessage(ctx, caption, [image], `[Image] ${caption}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to process image';
      await ctx.reply(`Error: ${message}`);
    }
  });

  bot.on('message:document', async (ctx) => {
    const doc = ctx.message.document;
    const mime = doc.mime_type ?? '';
    if (!IMAGE_MIME_TYPES.has(mime)) {
      await ctx.reply('Unsupported file type. I can only process images (JPEG, PNG, WebP, GIF).');
      return;
    }

    const caption = ctx.message.caption || "What's in this document?";
    try {
      const image = await downloadTelegramFile(doc.file_id, mime);
      await handleUserMessage(
        ctx,
        caption,
        [image],
        `[Document: ${doc.file_name ?? 'image'}] ${caption}`,
      );
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to process document';
      await ctx.reply(`Error: ${message}`);
    }
  });

  // ── Register command menu in Telegram UI ──
  bot.api
    .setMyCommands([
      { command: 'new', description: 'Start a new conversation' },
      { command: 'memory', description: 'View shared memory' },
      { command: 'sessions', description: 'List recent sessions' },
      { command: 'switch', description: 'Switch to a session by ID prefix' },
      { command: 'alerts', description: 'View alert settings' },
    ])
    .catch(() => {});

  // ── Catch unhandled errors so the polling loop keeps running ──
  bot.catch((err) => {
    console.error('[Telegram] Unhandled error in bot handler:', err.message ?? err);
  });

  // ── Start long polling ──
  bot.start({
    onStart: () => console.log('[Telegram] Bot started (long polling)'),
  });
}

export async function stopTelegramBot(): Promise<void> {
  if (bot) {
    await bot.stop();
    bot = null;
  }
}

export async function restartTelegramBot(): Promise<void> {
  await stopTelegramBot();
  startTelegramBot();
}
