<script setup lang="ts">
import { ref, onMounted } from 'vue';
import {
  getAlertSettings,
  updateAlertSettings,
  resetAlertSettings,
  sendTestAlert,
  type AlertSettings,
} from '../api/client';
import { SettingsGroup, SettingsRow } from '@/components/ui/settings-group';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import {
  CheckCircle,
  AlertCircle,
  RotateCcw,
  SendHorizonal,
  Info,
  Sparkles,
} from 'lucide-vue-next';
const ALERT_HINTS = {
  postScrape:
    'Runs after each scrape. An AI agent analyzes new transactions and spending patterns, alerting only when something noteworthy is found.',
  monthlySummary:
    "Sent once a month at 9:00 AM on your configured day. An AI agent summarizes last month's finances with contextual insights.",
} as const;

const loading = ref(true);
const saving = ref(false);
const error = ref('');
const success = ref('');
const testSending = ref(false);

const settings = ref<AlertSettings>({
  enabled: true,
  largeChargeThreshold: 500,
  unusualSpendingPercent: 30,
  monthlySummary: { enabled: true, dayOfMonth: 1 },
  reportScrapeErrors: true,
});

onMounted(async () => {
  try {
    const data = await getAlertSettings();
    settings.value = data;
  } catch (e: unknown) {
    error.value = (e instanceof Error ? e.message : '') || 'Failed to load alert settings';
  } finally {
    loading.value = false;
  }
});

async function save() {
  saving.value = true;
  error.value = '';
  success.value = '';
  try {
    const data = await updateAlertSettings(settings.value);
    settings.value = data;
    success.value = 'Settings saved';
    setTimeout(() => {
      success.value = '';
    }, 3000);
  } catch (e: unknown) {
    error.value = (e instanceof Error ? e.message : '') || 'Failed to save';
  } finally {
    saving.value = false;
  }
}

async function reset() {
  saving.value = true;
  error.value = '';
  try {
    const data = await resetAlertSettings();
    settings.value = data;
    success.value = 'Reset to defaults';
    setTimeout(() => {
      success.value = '';
    }, 3000);
  } catch (e: unknown) {
    error.value = (e instanceof Error ? e.message : '') || 'Failed to reset';
  } finally {
    saving.value = false;
  }
}

async function testAlert() {
  testSending.value = true;
  error.value = '';
  try {
    await sendTestAlert();
    success.value = 'Test alert sent to Telegram';
    setTimeout(() => {
      success.value = '';
    }, 3000);
  } catch (e: unknown) {
    error.value = (e instanceof Error ? e.message : '') || 'Failed to send test alert';
  } finally {
    testSending.value = false;
  }
}
</script>

<template>
  <div class="max-w-2xl mx-auto space-y-5 overflow-y-auto flex-1">
    <Teleport to="#toolbar-actions">
      <div class="flex items-center gap-2">
        <div v-if="success" class="flex items-center gap-1.5 text-[13px] text-success">
          <CheckCircle class="h-3.5 w-3.5" />
          {{ success }}
        </div>
        <div v-if="error" class="flex items-center gap-1.5 text-[13px] text-destructive">
          <AlertCircle class="h-3.5 w-3.5" />
          {{ error }}
        </div>
        <Button variant="secondary" size="sm" :disabled="saving" @click="reset">
          <RotateCcw class="h-3 w-3 mr-1.5" />
          Reset
        </Button>
        <Button variant="secondary" size="sm" :disabled="testSending" @click="testAlert">
          <SendHorizonal class="h-3 w-3 mr-1.5" />
          {{ testSending ? 'Sending…' : 'Test' }}
        </Button>
        <Button size="sm" :disabled="saving" @click="save">
          {{ saving ? 'Saving…' : 'Save' }}
        </Button>
      </div>
    </Teleport>

    <template v-if="!loading">
      <!-- Master Switch -->
      <SettingsGroup>
        <SettingsRow
          label="Enable Alerts"
          description="Master switch for all Telegram notifications"
        >
          <Switch v-model="settings.enabled" />
        </SettingsRow>
      </SettingsGroup>

      <!-- AI approach description -->
      <div
        :class="{ 'opacity-50 pointer-events-none': !settings.enabled }"
        class="flex items-start gap-2.5 text-[12px] text-text-secondary bg-primary/8 border border-primary/15 rounded-lg px-3 py-2.5"
      >
        <Sparkles class="h-4 w-4 text-primary flex-shrink-0 mt-0.5" />
        <span>
          Alerts are generated by an AI agent that autonomously investigates your financial data —
          transactions, spending patterns, balances, and net worth. It only sends a message when
          something genuinely noteworthy is found. The thresholds below guide the agent's analysis.
        </span>
      </div>

      <!-- Post-Scrape Analysis -->
      <SettingsGroup
        title="Post-Scrape Analysis"
        description="After each scrape, the agent reviews new transactions and spending patterns"
        :class="{ 'opacity-50 pointer-events-none': !settings.enabled }"
      >
        <SettingsRow class="bg-bg-secondary/30 text-[11px] text-text-tertiary">
          <div class="flex items-start gap-1.5">
            <Info class="h-3 w-3 mt-0.5 flex-shrink-0" />
            {{ ALERT_HINTS.postScrape }}
          </div>
        </SettingsRow>
        <SettingsRow label="Large charge threshold (₪)">
          <Input
            v-model.number="settings.largeChargeThreshold"
            type="number"
            class="w-28 h-8 text-[13px]"
            min="0"
          />
        </SettingsRow>
        <SettingsRow label="Unusual spending threshold (%)">
          <Input
            v-model.number="settings.unusualSpendingPercent"
            type="number"
            class="w-28 h-8 text-[13px]"
            min="10"
            max="200"
          />
        </SettingsRow>
        <SettingsRow label="Report scrape errors">
          <Switch v-model="settings.reportScrapeErrors" />
        </SettingsRow>
      </SettingsGroup>

      <!-- Monthly Summary -->
      <SettingsGroup
        title="Monthly Summary"
        description="A comprehensive AI-generated review of last month's finances"
        :class="{ 'opacity-50 pointer-events-none': !settings.enabled }"
      >
        <SettingsRow class="bg-bg-secondary/30 text-[11px] text-text-tertiary">
          <div class="flex items-start gap-1.5">
            <Info class="h-3 w-3 mt-0.5 flex-shrink-0" />
            {{ ALERT_HINTS.monthlySummary }}
          </div>
        </SettingsRow>
        <SettingsRow label="Enabled">
          <Switch v-model="settings.monthlySummary.enabled" />
        </SettingsRow>
        <SettingsRow v-if="settings.monthlySummary.enabled" label="Day of month to send">
          <Input
            v-model.number="settings.monthlySummary.dayOfMonth"
            type="number"
            class="w-28 h-8 text-[13px]"
            min="1"
            max="28"
          />
        </SettingsRow>
      </SettingsGroup>
    </template>

    <!-- Loading skeleton -->
    <template v-else>
      <div v-for="i in 3" :key="i" class="h-24 bg-bg-secondary animate-pulse rounded-xl" />
    </template>
  </div>
</template>
