// DO NOT EDIT BY HAND.
// Generated by scripts/generate-canonical-clients.ts from docs/api/v1.openapi.json.
import {
  canonicalErrorEnvelopeSchema as canonicalErrorEnvelopeSchemaValidator,
  diagnosticsResponseSchema as diagnosticsResponseSchemaValidator,
  pairingStatusResponseSchema as pairingStatusResponseSchemaValidator,
  referenceCommandRequestSchema as referenceCommandRequestSchemaValidator,
  referenceCommandResponseSchema as referenceCommandResponseSchemaValidator,
  referenceDeleteResponseSchema as referenceDeleteResponseSchemaValidator,
  referenceResponseSchema as referenceResponseSchemaValidator,
  referenceUpdateRequestSchema as referenceUpdateRequestSchemaValidator,
} from './contract.js';

export type Money = { value: string; currencyCode: string };
export type CanonicalMeta = {
  apiVersion: '1';
  generatedAt: string;
  source: 'mac-authoritative';
  calculationVersion?: string;
  completeness?: 'complete' | 'partial';
  estimated?: boolean;
  resourceVersion?: number;
  refreshHints?: Array<{ domain: string; resourceIds: Array<number> }>;
  receipt?: { idempotencyKey: string; replayed: boolean };
};
export type CanonicalErrorEnvelope = {
  error: {
    code:
      | 'authentication_required'
      | 'authentication_invalid'
      | 'mac_only'
      | 'pairing_required'
      | 'validation_error'
      | 'resource_not_found'
      | 'resource_conflict'
      | 'idempotency_key_required'
      | 'idempotency_key_reused'
      | 'unknown_outcome'
      | 'route_not_found'
      | 'internal_server_error';
    message: string;
    resourceId?: number;
    expectedVersion?: number;
    currentVersion?: number;
  };
  meta: {
    apiVersion: '1';
    requestId: string;
    refreshHints?: Array<{ domain: string; resourceIds: Array<number> }>;
  };
};
export type ReferenceResource = {
  id: number;
  title: string;
  amount: { value: string; currencyCode: string };
  resourceVersion: number;
  updatedAt: string;
};
export type ReferenceResponseData = {
  id: number;
  title: string;
  amount: { value: string; currencyCode: string };
  resourceVersion: number;
  updatedAt: string;
};
export type ReferenceResponse = {
  data: ReferenceResponseData;
  meta: {
    apiVersion: '1';
    generatedAt: string;
    source: 'mac-authoritative';
    calculationVersion: 'canonical-foundation-1';
    completeness: 'complete';
    estimated: false;
    resourceVersion?: number;
    refreshHints?: Array<{ domain: string; resourceIds: Array<number> }>;
    receipt?: { idempotencyKey: string; replayed: boolean };
  };
};
export type ReferenceReadQuery = { id?: number };
export type ReferenceUpdateRequest = {
  expectedVersion: number;
  title?: string;
  amount?: { value: string; currencyCode: string };
};
export type ReferenceDeleteResponseData = { deletedId: number };
export type ReferenceDeleteResponse = {
  data: ReferenceDeleteResponseData;
  meta: {
    apiVersion: '1';
    generatedAt: string;
    source: 'mac-authoritative';
    calculationVersion?: string;
    completeness?: 'complete' | 'partial';
    estimated?: boolean;
    resourceVersion?: number;
    refreshHints: Array<{ domain: string; resourceIds: Array<number> }>;
    receipt?: { idempotencyKey: string; replayed: boolean };
  };
};
export type ReferenceDeleteQuery = { expectedVersion: number };
export type ReferenceCommandRequest = {
  resourceId: number;
  idempotencyKey: string;
  command: 'refresh';
};
export type ReferenceCommandResponse = {
  data: { accepted: true; resourceId: number };
  meta: {
    apiVersion: '1';
    generatedAt: string;
    source: 'mac-authoritative';
    calculationVersion?: string;
    completeness?: 'complete' | 'partial';
    estimated?: boolean;
    resourceVersion?: number;
    refreshHints: Array<{ domain: string; resourceIds: Array<number> }>;
    receipt: { idempotencyKey: string; replayed: boolean };
  };
};
export type DiagnosticsResponse = {
  data: { listener: 'mac-local'; capabilities: Array<'canonical-api'> };
  meta: {
    apiVersion: '1';
    generatedAt: string;
    source: 'mac-authoritative';
    calculationVersion?: string;
    completeness?: 'complete' | 'partial';
    estimated?: boolean;
    resourceVersion?: number;
    refreshHints?: Array<{ domain: string; resourceIds: Array<number> }>;
    receipt?: { idempotencyKey: string; replayed: boolean };
  };
};
export type PairingStatusResponse = {
  data: { paired: true; deviceId: string };
  meta: {
    apiVersion: '1';
    generatedAt: string;
    source: 'mac-authoritative';
    calculationVersion?: string;
    completeness?: 'complete' | 'partial';
    estimated?: boolean;
    resourceVersion?: number;
    refreshHints?: Array<{ domain: string; resourceIds: Array<number> }>;
    receipt?: { idempotencyKey: string; replayed: boolean };
  };
};

export interface CanonicalTransportRequest {
  method: string;
  url: string;
  headers: Record<string, string>;
  body?: unknown;
}

export type CanonicalTransport = (
  request: CanonicalTransportRequest,
) => Promise<{ status: number; json(): Promise<unknown> }>;

export class CanonicalClientError extends Error {
  constructor(
    readonly code: string,
    readonly status: number,
    readonly requestId?: string,
    readonly details: unknown = undefined,
  ) {
    super(`Canonical API request failed: ${code}`);
    this.name = 'CanonicalClientError';
  }
}

async function fetchTransport(request: CanonicalTransportRequest) {
  const response = await fetch(request.url, {
    method: request.method,
    headers: { accept: 'application/json', ...request.headers },
    ...(request.body === undefined ? {} : { body: JSON.stringify(request.body) }),
  });
  return { status: response.status, json: () => response.json() as Promise<unknown> };
}

export interface CanonicalClientOptions {
  baseUrl: string;
  token: string;
  transport?: CanonicalTransport;
  testUnknownOutcome?: boolean;
}

const validators = {
  CanonicalErrorEnvelope: canonicalErrorEnvelopeSchemaValidator,
  DiagnosticsResponse: diagnosticsResponseSchemaValidator,
  PairingStatusResponse: pairingStatusResponseSchemaValidator,
  ReferenceCommandRequest: referenceCommandRequestSchemaValidator,
  ReferenceCommandResponse: referenceCommandResponseSchemaValidator,
  ReferenceDeleteResponse: referenceDeleteResponseSchemaValidator,
  ReferenceResponse: referenceResponseSchemaValidator,
  ReferenceUpdateRequest: referenceUpdateRequestSchemaValidator,
} as const;

export class CanonicalApiClient {
  private readonly baseUrl: string;
  private readonly token: string;
  private readonly transport: CanonicalTransport;
  private readonly testUnknownOutcome: boolean;

  constructor(options: CanonicalClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/$/, '');
    this.token = options.token;
    this.transport = options.transport ?? fetchTransport;
    this.testUnknownOutcome = options.testUnknownOutcome ?? false;
  }

  public getReference(id: number = 1): Promise<ReferenceResponseData> {
    const query = new URLSearchParams();
    if (id !== undefined) query.set('id', String(id));
    const suffix = query.toString() ? `?${query.toString()}` : '';
    return this.request<ReferenceResponse>(
      'GET',
      `/api/v1/reference${suffix}`,
      undefined,
      'ReferenceResponse',
    ).then((response) => response.data);
  }

  public updateReference(
    id: number,
    request: ReferenceUpdateRequest,
  ): Promise<ReferenceResponseData> {
    return this.request<ReferenceResponse>(
      'PATCH',
      `/api/v1/reference/${id}`,
      request,
      'ReferenceResponse',
    ).then((response) => response.data);
  }

  public deleteReference(
    id: number,
    expectedVersion: number,
  ): Promise<ReferenceDeleteResponseData> {
    const query = new URLSearchParams();
    query.set('expectedVersion', String(expectedVersion));
    const suffix = query.toString() ? `?${query.toString()}` : '';
    return this.request<ReferenceDeleteResponse>(
      'DELETE',
      `/api/v1/reference/${id}${suffix}`,
      undefined,
      'ReferenceDeleteResponse',
    ).then((response) => response.data);
  }

  public requestReferenceRefresh(
    request: ReferenceCommandRequest,
  ): Promise<ReferenceCommandResponse> {
    return this.request<ReferenceCommandResponse>(
      'POST',
      `/api/v1/reference/commands/refresh`,
      request,
      'ReferenceCommandResponse',
      this.testUnknownOutcome ? { 'x-canonical-test-unknown': 'true' } : undefined,
    );
  }

  public getDiagnostics(): Promise<DiagnosticsResponse> {
    return this.request<DiagnosticsResponse>(
      'GET',
      `/api/v1/diagnostics`,
      undefined,
      'DiagnosticsResponse',
    );
  }

  public getPairingStatus(): Promise<PairingStatusResponse> {
    return this.request<PairingStatusResponse>(
      'GET',
      `/api/v1/pairing/status`,
      undefined,
      'PairingStatusResponse',
    );
  }

  public requestRefresh(request: ReferenceCommandRequest): Promise<ReferenceCommandResponse> {
    return this.requestReferenceRefresh(request);
  }

  public async requestRefreshWithRecovery(request: ReferenceCommandRequest) {
    try {
      return { status: 'accepted' as const, response: await this.requestRefresh(request) };
    } catch (error) {
      if (error instanceof CanonicalClientError && error.code !== 'unknown_outcome') throw error;
      try {
        return { status: 'accepted' as const, response: await this.requestRefresh(request) };
      } catch (retryError) {
        if (retryError instanceof CanonicalClientError && retryError.code !== 'unknown_outcome')
          throw retryError;
        return {
          status: 'unknown' as const,
          resource: await this.getReference(request.resourceId),
        };
      }
    }
  }

  private async request<T>(
    method: string,
    path: string,
    body: unknown,
    responseName: keyof typeof validators,
    extraHeaders: Record<string, string> | undefined = undefined,
  ): Promise<T> {
    const response = await this.transport({
      method,
      url: `${this.baseUrl}${path}`,
      headers: {
        authorization: `Bearer ${this.token}`,
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
        ...extraHeaders,
      },
      ...(body === undefined ? {} : { body }),
    });
    const payload = await response.json();
    if (response.status < 200 || response.status >= 300) {
      const parsedError = validators.CanonicalErrorEnvelope.safeParse(payload);
      if (parsedError.success) {
        throw new CanonicalClientError(
          parsedError.data.error.code,
          response.status,
          parsedError.data.meta.requestId,
          parsedError.data.error,
        );
      }
      throw new CanonicalClientError('internal_server_error', response.status);
    }
    const parsed = validators[responseName].safeParse(payload);
    if (!parsed.success) throw new CanonicalClientError('invalid_response', response.status);
    return parsed.data as T;
  }
}

export class CanonicalMacClient extends CanonicalApiClient {}
export class CanonicalIPhoneClient extends CanonicalApiClient {}
