/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
export type paths = {
  '/api/v1/diagnostics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read trusted Mac diagnostics */
    get: operations['getDiagnostics'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/pairing/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read paired-device status */
    get: operations['getPairingStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reference': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the canonical foundation resource */
    get: operations['getReference'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reference/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete the canonical foundation resource */
    delete: operations['deleteReference'];
    options?: never;
    head?: never;
    /** Update the canonical foundation resource */
    patch: operations['updateReference'];
    trace?: never;
  };
  '/api/v1/reference/commands/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a receipt-protected refresh */
    post: operations['requestReferenceRefresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    CanonicalErrorEnvelope: {
      error: {
        /** @enum {string} */
        code:
          | 'authentication_required'
          | 'authentication_invalid'
          | 'mac_only'
          | 'pairing_required'
          | 'validation_error'
          | 'resource_not_found'
          | 'resource_conflict'
          | 'idempotency_key_required'
          | 'idempotency_key_reused'
          | 'unknown_outcome'
          | 'route_not_found'
          | 'internal_server_error';
        currentVersion?: number;
        expectedVersion?: number;
        message: string;
        resourceId?: number;
      };
      meta: {
        /** @constant */
        apiVersion: '1';
        refreshHints?: {
          domain: string;
          resourceIds: number[];
        }[];
        requestId: string;
      };
    };
    CanonicalMeta: {
      /** @constant */
      apiVersion: '1';
      calculationVersion?: string;
      /** @enum {string} */
      completeness?: 'complete' | 'partial';
      estimated?: boolean;
      /** Format: date-time */
      generatedAt: string;
      receipt?: {
        idempotencyKey: string;
        replayed: boolean;
      };
      refreshHints?: {
        domain: string;
        resourceIds: number[];
      }[];
      resourceVersion?: number;
      /** @constant */
      source: 'mac-authoritative';
    };
    DiagnosticsResponse: {
      data: {
        capabilities: 'canonical-api'[];
        /** @constant */
        listener: 'mac-local';
      };
      meta: {
        /** @constant */
        apiVersion: '1';
        calculationVersion?: string;
        /** @enum {string} */
        completeness?: 'complete' | 'partial';
        estimated?: boolean;
        /** Format: date-time */
        generatedAt: string;
        receipt?: {
          idempotencyKey: string;
          replayed: boolean;
        };
        refreshHints?: {
          domain: string;
          resourceIds: number[];
        }[];
        resourceVersion?: number;
        /** @constant */
        source: 'mac-authoritative';
      };
    };
    Money: {
      currencyCode: string;
      value: string;
    };
    PairingStatusResponse: {
      data: {
        deviceId: string;
        /** @constant */
        paired: true;
      };
      meta: {
        /** @constant */
        apiVersion: '1';
        calculationVersion?: string;
        /** @enum {string} */
        completeness?: 'complete' | 'partial';
        estimated?: boolean;
        /** Format: date-time */
        generatedAt: string;
        receipt?: {
          idempotencyKey: string;
          replayed: boolean;
        };
        refreshHints?: {
          domain: string;
          resourceIds: number[];
        }[];
        resourceVersion?: number;
        /** @constant */
        source: 'mac-authoritative';
      };
    };
    ReferenceCommandRequest: {
      /** @constant */
      command: 'refresh';
      idempotencyKey: string;
      resourceId: number;
    };
    ReferenceCommandResponse: {
      data: {
        /** @constant */
        accepted: true;
        resourceId: number;
      };
      meta: {
        /** @constant */
        apiVersion: '1';
        calculationVersion?: string;
        /** @enum {string} */
        completeness?: 'complete' | 'partial';
        estimated?: boolean;
        /** Format: date-time */
        generatedAt: string;
        receipt: {
          idempotencyKey: string;
          replayed: boolean;
        };
        refreshHints: {
          domain: string;
          resourceIds: number[];
        }[];
        resourceVersion?: number;
        /** @constant */
        source: 'mac-authoritative';
      };
    };
    ReferenceDeleteQuery: {
      expectedVersion: number;
    };
    ReferenceDeleteResponse: {
      data: {
        deletedId: number;
      };
      meta: {
        /** @constant */
        apiVersion: '1';
        calculationVersion?: string;
        /** @enum {string} */
        completeness?: 'complete' | 'partial';
        estimated?: boolean;
        /** Format: date-time */
        generatedAt: string;
        receipt?: {
          idempotencyKey: string;
          replayed: boolean;
        };
        refreshHints: {
          domain: string;
          resourceIds: number[];
        }[];
        resourceVersion?: number;
        /** @constant */
        source: 'mac-authoritative';
      };
    };
    ReferenceReadQuery: {
      id?: number;
    };
    ReferenceResource: {
      amount: {
        currencyCode: string;
        value: string;
      };
      id: number;
      resourceVersion: number;
      title: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ReferenceResponse: {
      data: {
        amount: {
          currencyCode: string;
          value: string;
        };
        id: number;
        resourceVersion: number;
        title: string;
        /** Format: date-time */
        updatedAt: string;
      };
      meta: {
        /** @constant */
        apiVersion: '1';
        /** @constant */
        calculationVersion: 'canonical-foundation-1';
        /** @constant */
        completeness: 'complete';
        /** @constant */
        estimated: false;
        /** Format: date-time */
        generatedAt: string;
        receipt?: {
          idempotencyKey: string;
          replayed: boolean;
        };
        refreshHints?: {
          domain: string;
          resourceIds: number[];
        }[];
        resourceVersion?: number;
        /** @constant */
        source: 'mac-authoritative';
      };
    };
    ReferenceUpdateRequest: {
      amount?: {
        currencyCode: string;
        value: string;
      };
      expectedVersion: number;
      title?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  getDiagnostics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stable coded error */
      '4XX': {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CanonicalErrorEnvelope'];
        };
      };
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DiagnosticsResponse'];
        };
      };
    };
  };
  getPairingStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stable coded error */
      '4XX': {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CanonicalErrorEnvelope'];
        };
      };
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PairingStatusResponse'];
        };
      };
    };
  };
  getReference: {
    parameters: {
      query?: {
        id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stable coded error */
      '4XX': {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CanonicalErrorEnvelope'];
        };
      };
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReferenceResponse'];
        };
      };
    };
  };
  deleteReference: {
    parameters: {
      query: {
        expectedVersion: number;
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stable coded error */
      '4XX': {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CanonicalErrorEnvelope'];
        };
      };
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReferenceDeleteResponse'];
        };
      };
    };
  };
  updateReference: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReferenceUpdateRequest'];
      };
    };
    responses: {
      /** @description Stable coded error */
      '4XX': {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CanonicalErrorEnvelope'];
        };
      };
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReferenceResponse'];
        };
      };
    };
  };
  requestReferenceRefresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReferenceCommandRequest'];
      };
    };
    responses: {
      /** @description Stable coded error */
      '4XX': {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CanonicalErrorEnvelope'];
        };
      };
      /** @description Successful response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReferenceCommandResponse'];
        };
      };
    };
  };
}
export enum ApiPaths {
  getReference = '/api/v1/reference',
  updateReference = '/api/v1/reference/{id}',
  deleteReference = '/api/v1/reference/{id}',
  requestReferenceRefresh = '/api/v1/reference/commands/refresh',
  getDiagnostics = '/api/v1/diagnostics',
  getPairingStatus = '/api/v1/pairing/status',
}
