import { computed, ref, watchEffect } from 'vue';

export type LanguageChoice = 'system' | 'en' | 'he';
export type LanguageLabel = keyof typeof english;
const english = {
  home: 'Home',
  activity: 'Activity',
  explore: 'Explore',
  advisor: 'Advisor',
  review: 'Review',
  budgets: 'Budgets',
  subscriptions: 'Subscriptions',
  netWorth: 'Net worth',
  categories: 'Categories',
  accounts: 'Accounts',
  alerts: 'Alerts',
  scraping: 'Account sync',
  settings: 'Settings',
  yourMoney: 'Your money',
  onThisMac: 'On this Mac',
  planning: 'Planning',
  manage: 'Manage',
  monthlySpending: 'Monthly spending',
  cashFlow: 'Cash flow',
  categorySpending: 'Category spending',
  merchant: 'Merchant',
  assetDetails: 'Asset details',
  appLanguage: 'App language',
  systemDefault: 'System default',
  language: 'Language',
  english: 'English',
  hebrew: 'Hebrew',
  viewingSampleData: 'Viewing sample data',
  exitDemo: 'Exit demo',
  mainNavigation: 'Main navigation',
  everyone: 'Everyone',
  together: 'Together',
  unassigned: 'Unassigned',
  refresh: 'Refresh',
  retry: 'Retry',
  yourMoneyAtAGlance: 'Your money, at a glance',
  accountsNeedAttention: 'accounts need attention',
  month: 'Month',
  totalSpending: 'Total spending',
  viewActivity: 'View activity',
  loadingSpending: 'Loading spending…',
  sameAsLastMonth: 'Same as last month',
  more: 'more',
  less: 'less',
  thanLastMonth: 'than last month',
  dailyChartHint: 'Hover over the line to inspect each day',
  postedIncome: 'Posted income',
  netCashFlow: 'Net cash flow',
  whereItWent: 'Where it went',
  noSpendingThisMonth: 'No spending to show for this month.',
  needsAttention: 'Needs attention',
  sinceLastVisit: 'Since your last visit',
  newTransactions: 'new',
  spent: 'spent',
  toReview: 'to review',
  cleanFinancialInbox: 'Clean up your financial inbox',
  budgetNeedsAttention: 'Budget needs attention',
  checkLatestSync: 'Check the latest sync',
  everythingCurrent: 'Everything looks current',
  noActionNeeded: 'No action needed right now',
  budgetPace: 'Budget pace',
  ofPlanned: 'of',
  planned: 'planned',
  remaining: 'remaining',
  setBudgetForPace: 'Set a budget to see your spending pace',
  details: 'Details',
  couldNotLoad: 'Some financial data could not load. Try refreshing.',
  followChange: 'Follow a change to its cause',
  manageCategories: 'Manage categories',
  netReceived: 'Net received',
  noSpendingInMonth: 'No spending in this month.',
  compareMonths: 'Compare months',
  monthlyHistoryEmpty: 'Monthly history will appear after your first transactions.',
  exploreYourMoney: 'Explore your money',
  progressAgainstPlans: 'Progress against your plans',
  afterSpending: 'after spending',
  membershipsAndBills: 'Memberships and service bills',
  balanceHistoryAssets: 'Balance history and assets',
  categoryRules: 'Category rules',
  organizeSpending: 'Organize how spending is classified',
  allActivity: 'All activity',
  searchEveryTransaction: 'Search every transaction',
  incomeAndSpendingTogether: 'Income and spending, together',
  timeRange: 'Time range',
  incomeAndSpendingByMonth: 'Income and spending by month',
  better: 'better',
  worse: 'worse',
  thanPreviousMonth: 'than previous month',
  postedIncomeMinusSpending: 'Posted income minus spending',
  loadingCashFlow: 'Loading cash flow…',
  income: 'Income',
  spending: 'Spending',
  postedSpending: 'Posted spending',
  year: 'Year',
  months: 'months',
  atAGlance: 'at a glance',
  monthlyAverage: 'Monthly average',
  totalIncome: 'Total income',
  followFlow: 'Follow the flow',
  searchActivity: 'Search all activity…',
  allTypes: 'All types',
  banks: 'Banks',
  creditCards: 'Credit cards',
  allAccounts: 'All accounts',
  allCategories: 'All categories',
  uncategorized: 'Uncategorized',
  allOwners: 'All owners',
  startDate: 'Start date',
  endDate: 'End date',
  to: 'to',
  transactionStatus: 'Transaction status',
  anyStatus: 'Any status',
  completed: 'Completed',
  pending: 'Pending',
  moneyDirection: 'Money direction',
  inAndOut: 'In and out',
  included: 'Included',
  excluded: 'Excluded',
  needsReview: 'Needs review',
  clear: 'Clear',
  transactions: 'transactions',
  reportingDate: 'Reporting date',
  description: 'Description',
  amount: 'Amount',
  category: 'Category',
  owner: 'Owner',
  status: 'Status',
  account: 'Account',
  noTransactionsFound: 'No transactions found',
  adjustFilters: 'Try adjusting your filters',
  bankDate: 'Bank date',
  none: 'None',
  unknownMember: 'Unknown member',
  page: 'Page',
  of: 'of',
  previous: 'Previous',
  next: 'Next',
  originalAmount: 'Original amount',
  installment: 'Installment',
  type: 'Type',
  transactionNeedsReview: 'This transaction needs review.',
  includeInStatistics: 'Include in statistics',
  excludeFromStatistics: 'Exclude from statistics',
  confirmCategory: 'Confirm category',
  setEffectiveDate: 'Set effective date',
  effectiveDateExplanation:
    'Choose when this transaction counts in reports. Its bank date stays unchanged.',
  effectiveDate: 'Effective date',
  useBankDate: 'Use bank date',
  saving: 'Saving…',
  save: 'Save',
  monthly: 'Monthly',
  yearly: 'Yearly',
  monthlyBudget: 'Monthly budget',
  yearlyBudget: 'Yearly budget',
  newBudget: 'New budget',
  noBudgetsYet: 'No budgets yet',
  budgetEmptyHint: 'Set spending limits on categories to track where your money goes.',
  createBudget: 'Create budget',
  budget: 'budget',
  spentSelectedMonth: 'Spent in selected month',
  spentSelectedYear: 'Year to date through selected month',
  allOnTrack: 'All on track',
  overBudget: 'Over budget',
  alert: 'Alert',
  left: 'left',
  hideTransactions: 'Hide transactions',
  showTransactions: 'Show transactions',
  editBudget: 'Edit budget',
  name: 'Name',
  color: 'Color',
  period: 'Period',
  notifyAt: 'Notify at',
  percentOfBudget: '% of budget',
  search: 'Search…',
  noMatchFor: 'No match for',
  cancel: 'Cancel',
  saveChanges: 'Save changes',
  transactionsCounted: 'Transactions counted in this budget',
  loadingTransactions: 'Loading transactions…',
  noMatchingTransactions: 'No matching transactions in this period.',
  showMore: 'Show more',
  date: 'Date',
  currentCategory: 'Current category',
  reason: 'Reason',
  confidence: 'Confidence',
  actions: 'Actions',
  allClear: 'All clear!',
  noTransactionsNeedReview: 'No transactions need review',
  reviewTransactions: 'transactions need review',
  recategorize: 'Re-categorize',
  confirmCurrentCategory: 'Confirm current category',
  staleExchangeRates: 'Exchange rates unavailable — some values may be inaccurate',
  totalNetWorth: 'Total net worth',
  addFirstAsset: 'Add your first asset to start tracking net worth',
  addAsset: 'Add asset',
  add: 'Add',
  advanced: 'Advanced',
  liquidNetWorth: 'Liquid net worth',
  vsLastMonth: 'vs last month',
  allocationByType: 'Allocation by type',
  noDataYet: 'No data yet',
  netWorthTrend: 'Net worth trend',
  total: 'Total',
  liquid: 'Liquid',
  startTrackingAssets: 'Start tracking your assets to see net worth history',
  assets: 'Assets',
  bankBalances: 'Bank balances',
  liabilities: 'Liabilities',
  askAboutFinances: 'Ask me anything about your finances',
  advisorDescription:
    'I can analyze spending, track subscriptions, categorize transactions, and give budget advice',
  advisorPlaceholder: 'Ask about your finances… (Enter to send, Shift+Enter for newline)',
  askTopCategories: 'What are my top spending categories this month?',
  askFoodComparison: 'How much did I spend on food this month vs last month?',
  askSavings: 'How can I save money based on my spending?',
  askSubscriptions: 'What are my recurring subscriptions?',
  askCategorize: 'Categorize my uncategorized transactions',
  newChat: 'New chat',
  noConversations: 'No conversations yet',
  today: 'Today',
  yesterday: 'Yesterday',
  subscriptionsAndServices: 'Subscriptions & services',
  recurringIntro:
    'Repeating charges for subscriptions and service bills. Check uncertain matches below.',
  recurringLoadError: 'Recurring payments could not be loaded.',
  tryAgain: 'Try again',
  estimatedMonthly: 'Estimated monthly',
  aYear: 'a year',
  noSubscriptions: 'No subscriptions or services found yet',
  recurringEmptyHint: 'Confirm a suggestion below or wait for more matching charges.',
  payment: 'Payment',
  pattern: 'Pattern',
  usualCharge: 'Usual charge',
  lastCharged: 'Last charged',
  nextExpected: 'Next expected',
  charges: 'charges',
  around: 'Around',
  exclude: 'Exclude',
  include: 'Include',
  everyTwoMonths: 'Every 2 months',
  reviewRecurring: 'Review recurring payments',
  recurringReviewHint:
    'These repeat, but may be ordinary purchases. They are not in your estimate.',
  notRecurring: 'Not recurring',
  undo: 'Undo',
  paymentDetails: 'Payment details',
  paymentDetailsLoadError: 'Payment details could not be loaded.',
  estimatedPerYear: 'Estimated per year',
  chargesInPattern: 'Charges in this pattern',
  otherMerchantCharges: 'Other charges from this merchant',
  netCategorySpending: 'Net category spending',
  viewTransactions: 'View transactions',
  history: 'history',
  recentTransactions: 'Recent transactions',
  all: 'All',
  noCategorySpending: 'No spending in this category for the selected month.',
  merchantsAppear: 'Merchants will appear with transactions.',
  netSpending: 'Net spending',
  noMerchantTransactions:
    'No transactions with this merchant this month. Choose another month to explore.',
  howSpendingChanges: 'How your spending changes',
  categoryBreakdown: 'Category breakdown',
  noPostedSpending: 'No posted spending in this month.',
  addLiability: 'Add liability',
  noAssetsTracked: 'No assets tracked yet.',
  noLiabilitiesTracked: 'No liabilities tracked.',
  noPostedSpendingYet: 'No posted spending yet',
} as const;
const hebrew: Record<LanguageLabel, string> = {
  home: 'בית',
  activity: 'פעילות',
  explore: 'סקירה',
  advisor: 'יועץ',
  review: 'בדיקה',
  budgets: 'תקציבים',
  subscriptions: 'מינויים',
  netWorth: 'שווי נקי',
  categories: 'קטגוריות',
  accounts: 'חשבונות',
  alerts: 'התראות',
  scraping: 'סנכרון חשבונות',
  settings: 'הגדרות',
  yourMoney: 'הכסף שלך',
  onThisMac: 'ב-Mac הזה',
  planning: 'תכנון',
  manage: 'ניהול',
  monthlySpending: 'הוצאות חודשיות',
  cashFlow: 'תזרים מזומנים',
  categorySpending: 'הוצאות לפי קטגוריה',
  merchant: 'בית עסק',
  assetDetails: 'פרטי נכס',
  appLanguage: 'שפת האפליקציה',
  systemDefault: 'ברירת המחדל של המכשיר',
  language: 'שפה',
  english: 'אנגלית',
  hebrew: 'עברית',
  viewingSampleData: 'מציג נתונים לדוגמה',
  exitDemo: 'יציאה מהדגמה',
  mainNavigation: 'ניווט ראשי',
  everyone: 'כולם',
  together: 'ביחד',
  unassigned: 'ללא שיוך',
  refresh: 'רענון',
  retry: 'נסה שוב',
  yourMoneyAtAGlance: 'הכסף שלך במבט אחד',
  accountsNeedAttention: 'חשבונות דורשים טיפול',
  month: 'חודש',
  totalSpending: 'סך ההוצאות',
  viewActivity: 'צפייה בפעילות',
  loadingSpending: 'טוען הוצאות…',
  sameAsLastMonth: 'ללא שינוי מהחודש הקודם',
  more: 'יותר',
  less: 'פחות',
  thanLastMonth: 'מהחודש הקודם',
  dailyChartHint: 'העבירו את הסמן על הקו כדי לראות כל יום',
  postedIncome: 'הכנסות שנרשמו',
  netCashFlow: 'תזרים נטו',
  whereItWent: 'לאן הכסף הלך',
  noSpendingThisMonth: 'אין הוצאות להצגה החודש.',
  needsAttention: 'דורש טיפול',
  sinceLastVisit: 'מאז הביקור האחרון',
  newTransactions: 'חדשות',
  spent: 'הוצאו',
  toReview: 'לבדיקה',
  cleanFinancialInbox: 'סדרו את תיבת הפעילות הפיננסית',
  budgetNeedsAttention: 'התקציב דורש טיפול',
  checkLatestSync: 'בדקו את הסנכרון האחרון',
  everythingCurrent: 'הכול מעודכן',
  noActionNeeded: 'לא נדרשת פעולה כרגע',
  budgetPace: 'קצב התקציב',
  ofPlanned: 'מתוך',
  planned: 'שתוכננו',
  remaining: 'נותרו',
  setBudgetForPace: 'הגדירו תקציב כדי לראות את קצב ההוצאות',
  details: 'פרטים',
  couldNotLoad: 'לא ניתן לטעון חלק מהנתונים הפיננסיים. נסו לרענן.',
  followChange: 'גלו מה עומד מאחורי השינוי',
  manageCategories: 'ניהול קטגוריות',
  netReceived: 'התקבל נטו',
  noSpendingInMonth: 'אין הוצאות בחודש הזה.',
  compareMonths: 'השוואת חודשים',
  monthlyHistoryEmpty: 'היסטוריית החודשים תופיע לאחר העסקאות הראשונות.',
  exploreYourMoney: 'גלו את הכסף שלכם',
  progressAgainstPlans: 'התקדמות ביחס לתוכניות שלכם',
  afterSpending: 'לאחר הוצאות',
  membershipsAndBills: 'מנויים וחשבונות שירות',
  balanceHistoryAssets: 'היסטוריית יתרות ונכסים',
  categoryRules: 'כללי קטגוריות',
  organizeSpending: 'ארגון סיווג ההוצאות',
  allActivity: 'כל הפעילות',
  searchEveryTransaction: 'חיפוש בכל העסקאות',
  incomeAndSpendingTogether: 'הכנסות והוצאות יחד',
  timeRange: 'טווח זמן',
  incomeAndSpendingByMonth: 'הכנסות והוצאות לפי חודש',
  better: 'טוב יותר',
  worse: 'נמוך יותר',
  thanPreviousMonth: 'מהחודש הקודם',
  postedIncomeMinusSpending: 'הכנסות שנרשמו בניכוי הוצאות',
  loadingCashFlow: 'טוען תזרים מזומנים…',
  income: 'הכנסות',
  spending: 'הוצאות',
  postedSpending: 'הוצאות שנרשמו',
  year: 'שנה',
  months: 'חודשים',
  atAGlance: 'במבט אחד',
  monthlyAverage: 'ממוצע חודשי',
  totalIncome: 'סך ההכנסות',
  followFlow: 'עקבו אחר התזרים',
  searchActivity: 'חיפוש בכל הפעילות…',
  allTypes: 'כל הסוגים',
  banks: 'בנקים',
  creditCards: 'כרטיסי אשראי',
  allAccounts: 'כל החשבונות',
  allCategories: 'כל הקטגוריות',
  uncategorized: 'ללא קטגוריה',
  allOwners: 'כל השיוכים',
  startDate: 'תאריך התחלה',
  endDate: 'תאריך סיום',
  to: 'עד',
  transactionStatus: 'מצב העסקה',
  anyStatus: 'כל המצבים',
  completed: 'הושלם',
  pending: 'ממתין',
  moneyDirection: 'כיוון הכסף',
  inAndOut: 'נכנס ויוצא',
  included: 'כלול',
  excluded: 'לא כלול',
  needsReview: 'דורש בדיקה',
  clear: 'ניקוי',
  transactions: 'עסקאות',
  reportingDate: 'תאריך דיווח',
  description: 'תיאור',
  amount: 'סכום',
  category: 'קטגוריה',
  owner: 'שיוך',
  status: 'מצב',
  account: 'חשבון',
  noTransactionsFound: 'לא נמצאו עסקאות',
  adjustFilters: 'נסו לשנות את המסננים',
  bankDate: 'תאריך הבנק',
  none: 'ללא',
  unknownMember: 'בן בית לא ידוע',
  page: 'עמוד',
  of: 'מתוך',
  previous: 'הקודם',
  next: 'הבא',
  originalAmount: 'סכום מקורי',
  installment: 'תשלום',
  type: 'סוג',
  transactionNeedsReview: 'יש לבדוק את העסקה הזו.',
  includeInStatistics: 'לכלול בנתונים',
  excludeFromStatistics: 'להוציא מהנתונים',
  confirmCategory: 'אישור קטגוריה',
  setEffectiveDate: 'קביעת תאריך דיווח',
  effectiveDateExplanation: 'בחרו מתי העסקה תיכלל בדוחות. תאריך הבנק לא ישתנה.',
  effectiveDate: 'תאריך דיווח',
  useBankDate: 'שימוש בתאריך הבנק',
  saving: 'שומר…',
  save: 'שמירה',
  monthly: 'חודשי',
  yearly: 'שנתי',
  monthlyBudget: 'תקציב חודשי',
  yearlyBudget: 'תקציב שנתי',
  newBudget: 'תקציב חדש',
  noBudgetsYet: 'אין תקציבים עדיין',
  budgetEmptyHint: 'הגדירו מגבלות הוצאה לקטגוריות כדי לעקוב אחר הכסף שלכם.',
  createBudget: 'יצירת תקציב',
  budget: 'תקציב',
  spentSelectedMonth: 'הוצאות בחודש שנבחר',
  spentSelectedYear: 'מתחילת השנה ועד החודש שנבחר',
  allOnTrack: 'הכול במסלול',
  overBudget: 'חריגה מהתקציב',
  alert: 'התראה',
  left: 'נותרו',
  hideTransactions: 'הסתרת עסקאות',
  showTransactions: 'הצגת עסקאות',
  editBudget: 'עריכת תקציב',
  name: 'שם',
  color: 'צבע',
  period: 'תקופה',
  notifyAt: 'התרעה ב-',
  percentOfBudget: '% מהתקציב',
  search: 'חיפוש…',
  noMatchFor: 'לא נמצאה התאמה ל-',
  cancel: 'ביטול',
  saveChanges: 'שמירת שינויים',
  transactionsCounted: 'עסקאות שנכללו בתקציב הזה',
  loadingTransactions: 'טוען עסקאות…',
  noMatchingTransactions: 'אין עסקאות תואמות בתקופה זו.',
  showMore: 'הצגת עוד',
  date: 'תאריך',
  currentCategory: 'קטגוריה נוכחית',
  reason: 'סיבה',
  confidence: 'רמת ביטחון',
  actions: 'פעולות',
  allClear: 'הכול טופל!',
  noTransactionsNeedReview: 'אין עסקאות לבדיקה',
  reviewTransactions: 'עסקאות דורשות בדיקה',
  recategorize: 'שינוי קטגוריה',
  confirmCurrentCategory: 'אישור הקטגוריה הנוכחית',
  staleExchangeRates: 'שערי החליפין אינם זמינים — ייתכן שחלק מהסכומים אינם מדויקים',
  totalNetWorth: 'שווי נקי כולל',
  addFirstAsset: 'הוסיפו נכס ראשון כדי להתחיל לעקוב אחר השווי הנקי',
  addAsset: 'הוספת נכס',
  add: 'הוספה',
  advanced: 'אפשרויות מתקדמות',
  liquidNetWorth: 'שווי נקי נזיל',
  vsLastMonth: 'לעומת החודש הקודם',
  allocationByType: 'חלוקה לפי סוג',
  noDataYet: 'אין נתונים עדיין',
  netWorthTrend: 'מגמת השווי הנקי',
  total: 'כולל',
  liquid: 'נזיל',
  startTrackingAssets: 'התחילו לעקוב אחר נכסים כדי לראות את היסטוריית השווי הנקי',
  assets: 'נכסים',
  bankBalances: 'יתרות בנק',
  liabilities: 'התחייבויות',
  askAboutFinances: 'שאלו אותי כל דבר על הכספים שלכם',
  advisorDescription: 'אפשר לנתח הוצאות, לעקוב אחר מינויים, לסווג עסקאות ולקבל עצות על התקציב',
  advisorPlaceholder: 'שאלו על הכספים שלכם… (Enter לשליחה, Shift+Enter לשורה חדשה)',
  askTopCategories: 'מהן קטגוריות ההוצאה המובילות שלי החודש?',
  askFoodComparison: 'כמה הוצאתי על אוכל החודש לעומת החודש הקודם?',
  askSavings: 'איך אוכל לחסוך על סמך ההוצאות שלי?',
  askSubscriptions: 'אילו מינויים קבועים יש לי?',
  askCategorize: 'סווג את העסקאות שלי ללא קטגוריה',
  newChat: 'שיחה חדשה',
  noConversations: 'אין שיחות עדיין',
  today: 'היום',
  yesterday: 'אתמול',
  subscriptionsAndServices: 'מינויים ושירותים',
  recurringIntro: 'חיובים חוזרים על מינויים וחשבונות שירות. בדקו התאמות לא ודאיות בהמשך.',
  recurringLoadError: 'לא ניתן לטעון את התשלומים החוזרים.',
  tryAgain: 'נסו שוב',
  estimatedMonthly: 'הערכה חודשית',
  aYear: 'לשנה',
  noSubscriptions: 'לא נמצאו מינויים או שירותים עדיין',
  recurringEmptyHint: 'אשרו הצעה בהמשך או המתינו לחיובים תואמים נוספים.',
  payment: 'תשלום',
  pattern: 'דפוס',
  usualCharge: 'חיוב רגיל',
  lastCharged: 'חיוב אחרון',
  nextExpected: 'צפוי בהמשך',
  charges: 'חיובים',
  around: 'בסביבות',
  exclude: 'הוצאה',
  include: 'הכללה',
  everyTwoMonths: 'כל חודשיים',
  reviewRecurring: 'בדיקת תשלומים חוזרים',
  recurringReviewHint: 'החיובים חוזרים, אך ייתכן שאלו קניות רגילות. הם אינם נכללים בהערכה.',
  notRecurring: 'לא חוזר',
  undo: 'ביטול',
  paymentDetails: 'פרטי תשלום',
  paymentDetailsLoadError: 'לא ניתן לטעון את פרטי התשלום.',
  estimatedPerYear: 'הערכה שנתית',
  chargesInPattern: 'חיובים בדפוס הזה',
  otherMerchantCharges: 'חיובים אחרים מבית העסק הזה',
  netCategorySpending: 'הוצאות נטו בקטגוריה',
  viewTransactions: 'צפייה בעסקאות',
  history: 'היסטוריה',
  recentTransactions: 'עסקאות אחרונות',
  all: 'הכול',
  noCategorySpending: 'אין הוצאות בקטגוריה הזו בחודש שנבחר.',
  merchantsAppear: 'בתי עסק יופיעו לאחר שיהיו עסקאות.',
  netSpending: 'הוצאות נטו',
  noMerchantTransactions: 'אין עסקאות עם בית העסק הזה החודש. בחרו חודש אחר.',
  howSpendingChanges: 'איך ההוצאות שלכם משתנות',
  categoryBreakdown: 'פירוט לפי קטגוריה',
  noPostedSpending: 'אין הוצאות שנרשמו בחודש הזה.',
  addLiability: 'הוספת התחייבות',
  noAssetsTracked: 'לא נוספו נכסים עדיין.',
  noLiabilitiesTracked: 'לא נוספו התחייבויות.',
  noPostedSpendingYet: 'אין הוצאות שנרשמו עדיין',
};
const stored = localStorage.getItem('money-monitor-language');
export const languageChoice = ref<LanguageChoice>(
  stored === 'en' || stored === 'he' ? stored : 'system',
);
export const language = computed(() =>
  languageChoice.value === 'system'
    ? navigator.language.toLowerCase().startsWith('he')
      ? 'he'
      : 'en'
    : languageChoice.value,
);
export function setLanguageChoice(choice: LanguageChoice) {
  languageChoice.value = choice;
  localStorage.setItem('money-monitor-language', choice);
}
export function t(label: LanguageLabel) {
  return language.value === 'he' ? hebrew[label] : english[label];
}
watchEffect(() => {
  document.documentElement.lang = language.value;
  document.documentElement.dir = language.value === 'he' ? 'rtl' : 'ltr';
});
